name : SDS Addresses
title : Surrey Digital Services
brand : SDS Addresses
description : 
keyword : 
baseurl : /sds-addresses
url: https://surreydigitalservices.github.io # the base hostname & protocol for your site
email : info@folklabs.com
twitter_username: SurreyDS
github_username:  SurreyDigitalServices
disqus_shortname: surreydigitalservices 
github : https://github.com/surreydigitalservices/sds-addresses
author : Paul Mackay
analytics : UA-74647974-1
year : 2016
sd_phase : alpha
exclude :
  - node_modules
  - README.md


