name : SDS Addresses
brand : SDS Addresses
description : 
keyword : 
baseurl : /sds-addresses
email : info@folklabs.com
twitter : 
github : https://github.com/folklabs/sds-addresses
author : Paul Mackay
analytics : 
year : 2016
exclude :
  - node_modules
  - README.md


markdown: redcarpet
redcarpet:
  extensions: ["tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
